### ISSUE TITLE
Allow renaming of top level categories

### ISSUE THREAD

**Issue by schrauger** [schrauger/mint.com-customize-default-categories#4]
Someone wanted the ability to rename top level categories. This would let the user modify all categories, as you can natively add subcategories, and you can hide primary and built-in subcategories with this script. With renaming abilities, you could then tweak it to your heart's desire.

I won't add the ability to create new top-level categories, as that would require a major overhaul of the script and saving abilities. But renaming will probably simply be adding a hidden subcategory to any primary category, with a prefix (to let the script know to hide the subcategory) and the name desired for the parent category.

**Comment by polarbreeze** [comment]
I've just started using Mint and it's magnificent - brilliantly conceived and executed, well done! I am/was a long time Quicken user so you know where I'm coming from. That said, the inability to create categories is really a huge, HUGE shortcoming.  The idea of being able to at least RENAME the parent categories would indeed 99% solve that problem (for me anyhow). I was delighted to see you have that in the works - but WHEN?!!  Thanks.

**Comment by ejlerner** [comment]
The ability to rename top level categories (or an equivalent workaround) would be a wonderful enhancement to an already great customization. Thanks in advance for working on this!

**Comment by kristinmull** [comment]
I have GreaseMonkey installed in Firefox, and I checked that it is currently enabled.  But when I open the script (by clicking on mint.com_customize_default_categories.user.js), no prompts appear that will allow me to install it.  Is there a workaround?  Thanks!

**Comment by schrauger** [comment]
@krelmu Thanks for letting me know about the problem. It looks like there's a bug with the latest version of Firefox and GreaseMonkey. I've updated the Readme file with instructions on how to install the script. Basically, use GreaseMonkey to create a new script, then copy/paste my script into the new script editor.

**Comment by lx0n2acl** [comment]
any updates on this feature?

**Comment by lx0n2acl** [comment]
also, awesome script and thank you 👍

**Comment by schrauger** [comment]
Sorry, no updates on this. It will take a lot more work to implement than I originally thought. Saving a custom name is pretty easy (just have a hidden sub-category), but the problem is overwriting that category name everywhere on the page. 

Right now, my script only cares about the dropdown list and the 'manage categories' list. If you rename a category, though, you have to search a bunch of other places in the DOM for where it's referenced. Which means adding a lot of code and checks that aren't in the script.

**Comment by polarbreeze** [comment]
OK, how about instead of allowing renaming, just letting people add new top-level categories then? And the mechanism for creating custom subcategories for that already exists…?

**Comment by schrauger** [comment]
I've decided not to implement this feature. My script is limited to the category dropdown and doesn't affect any other parts of the transaction page or anything on other pages. To actually rename or create a top level category would require hooking into a ton of parts of other pages and as such is outside of the scope for this plugin.
