### ISSUE TITLE
Subcategories not being hidden

### ISSUE THREAD

**Issue by m00-bear** [schrauger/mint.com-customize-default-categories#5]
The UI part of the script is working great, and things are being struck-through and apparently saving appropriately, but subcategories are not being hidden.

The **main categories are working as expected**, and no longer show after saving the hidden categories, but no combination of subcategories are working for me. They all show, regardless of the fact that their checkboxes are checked and they are struck-through on the edit page.

I am a novice, but nothing stood out that I could see that would break the script. The
pop-categories-708
menu-category-708
are still the correct IDs in the actual page source.

Is this currently working for anyone else?

On Chrome with Tampermonkey:
Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by schrauger** [comment]
I'm seeing this problem as well. It looks like Mint has changed their site a bit and may be re-loading subcategories after they've already been loaded on the page.

I'll work on the script and try to fix this. Thanks for letting me know!

**Comment by vandevsr** [comment]
I experience the same bug and have the same chrome setup as m00-bear.
Looking closely as it loads, I'm seeing the hidden subcategories are hidden for a moment (like 0.2 sec), then show up again.

**Comment by sergiover** [comment]
Hi all! I'm experiencing the same issue on Chrome Version 65.0.3325.181 (Official Build) (64-bit) with Tampermonkey.

@schrauger: do you think this bug is fixable? Have you been able to make any progress?

Thanks for making this very useful script!

**Comment by ejlerner** [comment]
I have the same issue. Subcategories are momentarily hidden, then full list becomes and remains visible. As if the script is being overridden.

**Comment by ejlerner** [comment]
Seems fixed now?

**Comment by schrauger** [comment]
This issue is now fixed. I added a new function to create a global css rule to hide categories based on their element ID, which should keep them hidden even when Mint clears out element classes (which  caused them to become unhidden).
